export const ROBOTO_FONTS = {
  RobotoBold: "Roboto-Bold",
  RobotoBoldItalic: "Roboto-BoldItalic",
  RobotoItalic: "Roboto-Italic",
  RobotoLight: "Roboto-Light",
  RobotoLightItalic: "Roboto-LightItalic",
  RobotoMediumItalic: "Roboto-MediumItalic",
  RobotoRegular: "Roboto-Regular",
  RobotoThin: "Roboto-Thin",
  RobotoThinItalic: "Roboto-ThinItalic",
  Roboto: "Roboto",
  RobotoMedium: "Roboto-medium",
  RobotoBlack: "Roboto-Black",
  RobotoBlackItalic: "Roboto-BlackItalic",
};
