name: Publish to Firebase Distribution

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env
        run: touch .env
      - name: Add AUTH URL
        run: echo "REACT_APP_VIDEOSDK_TOKEN = ${{secrets.AUTH_TOKEN}}" >> .env

      # 2
      - name: Generate Release APK
        run: npm install --force && cd android && ./gradlew assembleRelease
      # 3
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
  deploy-firebase:
    # 1
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      # 2
      - uses: actions/download-artifact@main
        with:
          name: app-release.apk
      #3
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: react-native-android-demo
          file: app-release.apk
